version: '3.9'

services:
  front:
    build: .
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
    ports:
      - 13001:80
      - 13002:443
    networks:
      - frontend
    environment:
      - NODE_ENV=production

networks:
  frontend: